data:
  price_path: "data/raw_prices.parquet"
  force_download: false   # Only true if you want to redownload data
  use_sp500: true         # Automatically download all S&P 500 tickers
  etfs:                   # Additional etfs alongside S&P 500
    - SPY
    - QQQ
    - VOO
  tickers:                # Used only if use_sp500 is false
    - SPY
    - QQQ
    - IWM
    - XLF
    - XLK
  start_date: "2018-01-01"
  end_date: "2026-08-01"